export const projects = [
  {
    title: 'MeetMeFit App',
    description: "MeetMeFit is an app and a startup incubated at the New Jersey Innovation Institute that helps people find Fitness Buddies, Sports Partners and Gym Partners near them based on their fitness goals and level.",
    image: '/images/1.png',
    tags: ['Flutter', 'Dart', 'Firebase', 'Node', 'GCP', 'MERN'],
    source: 'https://google.com',
    visit: 'https://www.meetmefit.live/',
    id: 0,
  },
  {
    title: 'MeetMeFit Challenges App',
    description: "The MeetMeFit Chalengeds app is an app where users can take up exciting fitness challenges and earn physical rewards when they complete challenge tasks.",
    image: '/images/2.png',
    tags: ['Flutter', 'Dart', 'Firebase', 'Node', 'GCP'],
    source: 'https://google.com',
    visit: 'https://www.meetmefit.live/',
    id: 1,
  },
  {
    title: 'Fabric Fault Detection',
    description: "This is a project that consists of a model built using Convolutional Neural Networks(CNN) to detect faults in fabrics with over 80% accuracy which is 20% higher than the industry average.",
    image: '/images/3.png',
    tags: ['Python', 'CNN', 'AI', 'Data Science'],
    source: 'https://github.com/yashrandive/data_science_projects/tree/master/Fabric_Fault_Detection_CNN',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/Fabric_Fault_Detection_CNN',
    id: 2,
  },
  {
    title: 'Volkswagen Porcshe Buyout Analysis',
    description: "This is a project that consists of a full analysis and forecast of the stock prices of Folkswagen and Porche during their merger. We also compare the price fulctuations for the BMW stock during this timespan.",
    image: '/images/4.jpeg',
    tags: ['Python', 'Time Series', 'ARMA', 'Forecasting'],
    source: 'https://google.com',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/Folkswagen-Porsche%20Buyout%20%7C%20Time%20Series%20Analysis',
    id: 3,
  },
  {
    title: 'Online Advertisement Click Prediction',
    description: "In this project, I have modeled upon a publicly availble dataset to predict whether or not a person would click on an online advertisement",
    image: '/images/5.jpg',
    tags: ['Python', 'Logistic Regression', 'Data Science', 'Predictive Modeling'],
    source: 'https://google.com',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/avertisement_click_prediction',
    id: 4,
  },
  {
    title: 'Coronary Heart Disease Prediction',
    description: "In this project, I built a model that predicts whether an individual would suffer from a Coronary Heart Disease(CHD) in the next 10 years based various vital signs and parameters.",
    image: '/images/6.jpg',
    tags: ['Python', 'Predictive Modeling', 'Data Science',],
    source: 'https://google.com',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/Heart_Disease_Detection',
    id: 5,
  },
  {
    title: 'Restaurant Rating Prediction(NLP)',
    description: "This predictive model uses Sentiment Analysis to predict the Star Rating given by a customer based on a review written in text.",
    image: '/images/7.jpg',
    tags: ['Python', 'NLP', 'Data Science', 'Predictive Modeling'],
    source: 'https://google.com',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/Restaurant-Rating-Prediction',
    id: 6,
  },
  {
    title: 'Campus Placement Prediction(DNN)',
    description: "This is an analysis and prediction of whether a university student will get employed based on their academic history and professional experience using Deep Neural Networks.",
    image: '/images/8.jpg',
    tags: ['Python', 'Neural Networks', 'Data Science', 'Predictive Modeling'],
    source: 'https://google.com',
    visit: 'https://github.com/yashrandive/data_science_projects/tree/master/Campus%20Placement%20Prediction%20(95%25%20Accuracy)',
    id: 7,
  },
];

export const TimeLineData = [
  { year: 2014, text: 'Started my journey', },
  { year: 2015, text: 'Learnt Java, C, C++ and built small games', },
  { year: 2016, text: 'Became and Android Developer and built fitness related apps', },
  { year: 2017, text: 'Learnt Web Development and built small websites for myself and my university', },
  { year: 2018, text: 'Learnt Python and other web development frameworks, Built the first prototype for my startup, MeetMeFit on Kotlin(Android)', },
  { year: 2020, text: 'Worked as a Data Scientist for a start-up in the Silicon Valley and built the MVP for my startup using Flutter + Dart and Published it on the Google Play store', },
  { year: 2021, text: 'Built an Ed. Tech. Startup to teach kids across 5 countries how to code and formed a team for MeetMeFit', },
  { year: 2022, text: 'Began my Master\'s degree at NJIT and got a monetary grant for MeetMeFit. About to launch the app in the United States of America', },
  { year: 2023, text: 'Looking to work as a Software Development engineer with a tech company to make this world a better place', },
];